modLoader="javafml" #mandatory

loaderVersion="[36,)" #mandatory This is typically bumped every Minecraft version by Forge. See our download page for lists of versions.

license="All rights reserved"

[[mods]] #mandatory

modId="naturalists" #mandatory

version="0.0.1" #mandatory

displayName="Naturalists" #mandatory

logoFile="examplemod.png" #optional

credits="Credits go to the community who made this mod possible!" #optional

authors="noon, CircleF1sh, GLaDOS edition, amo, CactusKing, CreativityShark, crispytwig, and Kittyherz" #optional

description='''
The Naturalist Mod aims to breathe life into Minecraft by adding a plethora of animals to the game as well as some unique environments.
'''